"""PHASE 6 -- mesh writers.

Binary PLY is the deliverable; OBJ is a convenience for looking at the geometry
and nothing more.

Why PLY and not OBJ
-------------------
OBJ cannot carry the section 0.4 per-vertex channels.  It has positions,
normals and texture coordinates, and that is the whole format -- there is no
mechanism for arbitrary named scalars.  Exporting only OBJ would silently drop
``mss``, ``foam``, ``depth``, ``wdir`` and ``aniso``, which is everything that
makes this mesh worth generating rather than just displacing a plane.

PLY has custom per-vertex properties, and Mitsuba's PLY loader passes unknown
ones through as mesh attributes reachable from a custom BSDF as
``mesh_attribute`` textures.  That is the entire delivery path into Phase 7.

Binary rather than ASCII: about a quarter of the size and far faster to parse.
Little-endian, which is what every platform this runs on uses; the header says
so explicitly, so a big-endian reader would reject it rather than read garbage.

:func:`write_obj` exists because dropping a mesh into MeshLab or Blender to
check it looks right is a reasonable thing to want.  It logs what it discarded
rather than pretending the file is equivalent.
"""

from __future__ import annotations

import json
import subprocess
from datetime import datetime, timezone
from pathlib import Path

import numpy as np

__all__ = ["write_ply", "write_obj", "write_frame_metadata", "export_frame",
           "read_ply"]

_PLY_TYPES = {
    np.dtype(np.float32): "float",
    np.dtype(np.float64): "double",
    np.dtype(np.int32): "int",
    np.dtype(np.uint8): "uchar",
}


def _git_sha(root: Path | None = None) -> str:
    try:
        out = subprocess.run(["git", "rev-parse", "HEAD"],
                             cwd=str(root or Path(__file__).resolve().parent.parent),
                             capture_output=True, text=True, timeout=10)
        return out.stdout.strip() or "unknown"
    except Exception:
        return "unknown"


# ---------------------------------------------------------------------------
# PLY
# ---------------------------------------------------------------------------


def write_ply(mesh, path, *, channels: bool = True) -> Path:
    """Write a binary little-endian PLY with the per-vertex channels.

    Vertex properties are, in order: ``x y z nx ny nz`` then every channel in
    ``mesh.channels``, all float32. Faces are written with a ``uchar`` count and
    ``int`` indices, the convention every PLY reader expects.
    """
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)

    names = ["x", "y", "z", "nx", "ny", "nz"]
    cols = [mesh.vertices[:, 0], mesh.vertices[:, 1], mesh.vertices[:, 2],
            mesh.normals[:, 0], mesh.normals[:, 1], mesh.normals[:, 2]]
    if channels:
        for name in sorted(mesh.channels):
            names.append(name)
            cols.append(mesh.channels[name])

    vertex_dtype = np.dtype([(n, "<f4") for n in names])
    verts = np.empty(mesh.n_vertices, dtype=vertex_dtype)
    for n, c in zip(names, cols):
        verts[n] = np.asarray(c, dtype=np.float32)

    face_dtype = np.dtype([("n", "u1"), ("v", "<i4", (3,))])
    faces = np.empty(mesh.n_faces, dtype=face_dtype)
    faces["n"] = 3
    faces["v"] = mesh.faces.astype(np.int32)

    header = ["ply", "format binary_little_endian 1.0",
              f"comment generated by pywave at t = {mesh.meta.get('t', 0.0)} s",
              f"comment scene {mesh.meta.get('scene', 'unnamed')} "
              f"seed {mesh.meta.get('seed', '?')} "
              f"mesh_dx {mesh.meta.get('mesh_dx', '?')} m",
              f"element vertex {mesh.n_vertices}"]
    header += [f"property float {n}" for n in names]
    header += [f"element face {mesh.n_faces}",
               "property list uchar int vertex_indices", "end_header"]

    with path.open("wb") as fh:
        fh.write(("\n".join(header) + "\n").encode("ascii"))
        fh.write(verts.tobytes())
        fh.write(faces.tobytes())
    return path


def read_ply(path):
    """Minimal binary-PLY reader, for round-tripping our own output.

    Deliberately narrow: it handles the files :func:`write_ply` produces and
    nothing else. Its job is to let a test assert that the custom properties
    survive a write/read cycle -- the five-minute check cookbook 6.6 asks for
    before betting Phase 7 on it -- not to be a general PLY parser.
    """
    path = Path(path)
    with path.open("rb") as fh:
        if fh.readline().strip() != b"ply":
            raise ValueError(f"{path} is not a PLY file")
        fmt = fh.readline().strip()
        if fmt != b"format binary_little_endian 1.0":
            raise ValueError(f"unsupported PLY format: {fmt!r}")

        names, n_vertex, n_face, element = [], 0, 0, None
        while True:
            line = fh.readline()
            if not line:
                raise ValueError("unexpected end of PLY header")
            parts = line.split()
            if parts[0] == b"end_header":
                break
            if parts[0] == b"element":
                element = parts[1]
                if element == b"vertex":
                    n_vertex = int(parts[2])
                elif element == b"face":
                    n_face = int(parts[2])
            elif parts[0] == b"property" and element == b"vertex":
                if parts[1] != b"float":
                    raise ValueError(f"unsupported vertex property type {parts[1]!r}")
                names.append(parts[2].decode("ascii"))

        verts = np.frombuffer(fh.read(n_vertex * 4 * len(names)),
                              dtype=np.dtype([(n, "<f4") for n in names]))
        faces = np.frombuffer(fh.read(n_face * (1 + 12)),
                              dtype=np.dtype([("n", "u1"), ("v", "<i4", (3,))]))

    data = {n: np.array(verts[n]) for n in names}
    return data, np.array(faces["v"])


# ---------------------------------------------------------------------------
# OBJ
# ---------------------------------------------------------------------------


def write_obj(mesh, path, *, quiet: bool = False) -> Path:
    """Write a Wavefront OBJ. **Lossy** -- geometry and normals only.

    Every per-vertex channel is discarded, because OBJ has nowhere to put them.
    Use this to look at the mesh; use :func:`write_ply` for anything that feeds
    a renderer.
    """
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)

    dropped = sorted(mesh.channels)
    if dropped and not quiet:
        print(f"    note: OBJ cannot carry per-vertex channels; dropping "
              f"{', '.join(dropped)}. Use the PLY for rendering.")

    v = np.asarray(mesh.vertices, dtype=np.float64)
    n = np.asarray(mesh.normals, dtype=np.float64)
    f = np.asarray(mesh.faces, dtype=np.int64) + 1          # OBJ is 1-based

    with path.open("w", encoding="ascii", newline="\n") as fh:
        fh.write(f"# pywave water mesh, scene {mesh.meta.get('scene', 'unnamed')}, "
                 f"t = {mesh.meta.get('t', 0.0)} s\n")
        fh.write(f"# {mesh.n_vertices} vertices, {mesh.n_faces} faces, "
                 f"post spacing {mesh.meta.get('mesh_dx', '?')} m\n")
        if dropped:
            fh.write(f"# per-vertex channels NOT representable in OBJ: "
                     f"{', '.join(dropped)} -- see the PLY\n")
        np.savetxt(fh, v, fmt="v %.6f %.6f %.6f")
        np.savetxt(fh, n, fmt="vn %.6f %.6f %.6f")
        np.savetxt(fh, np.stack([f[:, 0], f[:, 0], f[:, 1], f[:, 1],
                                 f[:, 2], f[:, 2]], axis=1),
                   fmt="f %d//%d %d//%d %d//%d")
    return path


# ---------------------------------------------------------------------------
# Provenance
# ---------------------------------------------------------------------------


def write_frame_metadata(mesh, path, extra: dict | None = None) -> Path:
    """Sidecar JSON: everything needed to regenerate this exact frame.

    Cookbook 6.6 wants provenance per frame, and it is right about why -- when a
    signature question surfaces months later, the first thing anyone asks is
    what wind, what seed, what code produced that image.
    """
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)

    doc = dict(mesh.meta)
    doc.update({
        "git_sha": _git_sha(),
        "written_utc": f"{datetime.now(timezone.utc):%Y-%m-%d %H:%M:%S}",
        "n_vertices": mesh.n_vertices,
        "n_faces": mesh.n_faces,
        "channels": {
            name: {
                "min": float(np.min(arr)), "max": float(np.max(arr)),
                "mean": float(np.mean(arr)),
            } for name, arr in sorted(mesh.channels.items())
        },
    })
    if extra:
        doc.update(extra)
    path.write_text(json.dumps(doc, indent=2) + "\n", encoding="utf-8")
    return path


def export_frame(mesh, directory, stem: str = "water", *,
                 obj: bool = False, quiet: bool = False) -> dict:
    """Write ``<stem>.ply`` plus its metadata, and optionally an OBJ.

    Returns the paths written.
    """
    directory = Path(directory)
    out = {"ply": write_ply(mesh, directory / f"{stem}.ply"),
           "json": write_frame_metadata(mesh, directory / f"{stem}.json")}
    if obj:
        out["obj"] = write_obj(mesh, directory / f"{stem}.obj", quiet=quiet)
    return out
