"""PHASE 6 -- mesh writers.

Binary PLY is the deliverable; OBJ is a convenience for looking at the geometry
and nothing more.

Why PLY and not OBJ
-------------------
OBJ cannot carry the section 0.4 per-vertex channels.  It has positions,
normals and texture coordinates, and that is the whole format -- there is no
mechanism for arbitrary named scalars.  Exporting only OBJ would silently drop
``mss``, ``foam``, ``depth``, ``wdir`` and ``aniso``, which is everything that
makes this mesh worth generating rather than just displacing a plane.

PLY has custom per-vertex properties, and Mitsuba's PLY loader passes unknown
ones through as mesh attributes reachable from a custom BSDF as
``mesh_attribute`` textures.  That is the entire delivery path into Phase 7.

Binary rather than ASCII: about a quarter of the size and far faster to parse.
Little-endian, which is what every platform this runs on uses; the header says
so explicitly, so a big-endian reader would reject it rather than read garbage.

:func:`write_obj` exists because dropping a mesh into MeshLab or Blender to
check it looks right is a reasonable thing to want.  It logs what it discarded
rather than pretending the file is equivalent.
"""

from __future__ import annotations

import json
import subprocess
from datetime import datetime, timezone
from pathlib import Path

import numpy as np

from .channels import CHANNEL_UNITS

__all__ = ["write_ply", "write_obj", "write_frame_metadata", "export_frame",
           "read_ply", "mitsuba_scene_params", "mitsuba_scene_dict",
           "write_mitsuba_scene", "write_mitsuba_xml",
           "write_terrain_export"]



def _git_sha(root: Path | None = None) -> str:
    try:
        out = subprocess.run(["git", "rev-parse", "HEAD"],
                             cwd=str(root or Path(__file__).resolve().parent.parent),
                             capture_output=True, text=True, timeout=10)
        return out.stdout.strip() or "unknown"
    except Exception:
        return "unknown"


# ---------------------------------------------------------------------------
# PLY
# ---------------------------------------------------------------------------


def write_ply(mesh, path, *, channels: bool = True) -> Path:
    """Write a binary little-endian PLY with the per-vertex channels.

    Vertex properties are, in order: ``x y z nx ny nz`` then every channel in
    ``mesh.channels``, all float32. Faces are written with a ``uchar`` count and
    ``int`` indices, the convention every PLY reader expects.
    """
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)

    names = ["x", "y", "z", "nx", "ny", "nz"]
    cols = [mesh.vertices[:, 0], mesh.vertices[:, 1], mesh.vertices[:, 2],
            mesh.normals[:, 0], mesh.normals[:, 1], mesh.normals[:, 2]]
    if channels:
        for name in sorted(mesh.channels):
            names.append(name)
            cols.append(mesh.channels[name])

    vertex_dtype = np.dtype([(n, "<f4") for n in names])
    verts = np.empty(mesh.n_vertices, dtype=vertex_dtype)
    for n, c in zip(names, cols):
        verts[n] = np.asarray(c, dtype=np.float32)

    face_dtype = np.dtype([("n", "u1"), ("v", "<i4", (3,))])
    faces = np.empty(mesh.n_faces, dtype=face_dtype)
    faces["n"] = 3
    faces["v"] = mesh.faces.astype(np.int32)

    header = ["ply", "format binary_little_endian 1.0",
              f"comment generated by pywave at t = {mesh.meta.get('t', 0.0)} s",
              f"comment scene {mesh.meta.get('scene', 'unnamed')} "
              f"seed {mesh.meta.get('seed', '?')} "
              f"mesh_dx {mesh.meta.get('mesh_dx', '?')} m",
              f"element vertex {mesh.n_vertices}"]
    header += [f"property float {n}" for n in names]
    header += [f"element face {mesh.n_faces}",
               "property list uchar int vertex_indices", "end_header"]

    with path.open("wb") as fh:
        fh.write(("\n".join(header) + "\n").encode("ascii"))
        fh.write(verts.tobytes())
        fh.write(faces.tobytes())
    return path


def read_ply(path):
    """Minimal binary-PLY reader, for round-tripping our own output.

    Deliberately narrow: it handles the files :func:`write_ply` produces and
    nothing else. Its job is to let a test assert that the custom properties
    survive a write/read cycle -- the five-minute check cookbook 6.6 asks for
    before betting Phase 7 on it -- not to be a general PLY parser.
    """
    path = Path(path)
    with path.open("rb") as fh:
        if fh.readline().strip() != b"ply":
            raise ValueError(f"{path} is not a PLY file")
        fmt = fh.readline().strip()
        if fmt != b"format binary_little_endian 1.0":
            raise ValueError(f"unsupported PLY format: {fmt!r}")

        names, n_vertex, n_face, element = [], 0, 0, None
        while True:
            line = fh.readline()
            if not line:
                raise ValueError("unexpected end of PLY header")
            parts = line.split()
            if parts[0] == b"end_header":
                break
            if parts[0] == b"element":
                element = parts[1]
                if element == b"vertex":
                    n_vertex = int(parts[2])
                elif element == b"face":
                    n_face = int(parts[2])
            elif parts[0] == b"property" and element == b"vertex":
                if parts[1] != b"float":
                    raise ValueError(f"unsupported vertex property type {parts[1]!r}")
                names.append(parts[2].decode("ascii"))

        verts = np.frombuffer(fh.read(n_vertex * 4 * len(names)),
                              dtype=np.dtype([(n, "<f4") for n in names]))
        faces = np.frombuffer(fh.read(n_face * (1 + 12)),
                              dtype=np.dtype([("n", "u1"), ("v", "<i4", (3,))]))

    data = {n: np.array(verts[n]) for n in names}
    return data, np.array(faces["v"])


# ---------------------------------------------------------------------------
# OBJ
# ---------------------------------------------------------------------------


def write_obj(mesh, path, *, quiet: bool = False) -> Path:
    """Write a Wavefront OBJ. **Lossy** -- geometry and normals only.

    Every per-vertex channel is discarded, because OBJ has nowhere to put them.
    Use this to look at the mesh; use :func:`write_ply` for anything that feeds
    a renderer.
    """
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)

    dropped = sorted(mesh.channels)
    if dropped and not quiet:
        print(f"    note: OBJ cannot carry per-vertex channels; dropping "
              f"{', '.join(dropped)}. Use the PLY for rendering.")

    v = np.asarray(mesh.vertices, dtype=np.float64)
    n = np.asarray(mesh.normals, dtype=np.float64)
    f = np.asarray(mesh.faces, dtype=np.int64) + 1          # OBJ is 1-based

    with path.open("w", encoding="ascii", newline="\n") as fh:
        fh.write(f"# pywave water mesh, scene {mesh.meta.get('scene', 'unnamed')}, "
                 f"t = {mesh.meta.get('t', 0.0)} s\n")
        fh.write(f"# {mesh.n_vertices} vertices, {mesh.n_faces} faces, "
                 f"post spacing {mesh.meta.get('mesh_dx', '?')} m\n")
        if dropped:
            fh.write(f"# per-vertex channels NOT representable in OBJ: "
                     f"{', '.join(dropped)} -- see the PLY\n")
        np.savetxt(fh, v, fmt="v %.6f %.6f %.6f")
        np.savetxt(fh, n, fmt="vn %.6f %.6f %.6f")
        np.savetxt(fh, np.stack([f[:, 0], f[:, 0], f[:, 1], f[:, 1],
                                 f[:, 2], f[:, 2]], axis=1),
                   fmt="f %d//%d %d//%d %d//%d")
    return path


# ---------------------------------------------------------------------------
# Provenance
# ---------------------------------------------------------------------------


def write_frame_metadata(mesh, path, extra: dict | None = None) -> Path:
    """Sidecar JSON: everything needed to regenerate this exact frame.

    Cookbook 6.6 wants provenance per frame, and it is right about why -- when a
    signature question surfaces months later, the first thing anyone asks is
    what wind, what seed, what code produced that image.
    """
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)

    doc = dict(mesh.meta)
    doc.update({
        "git_sha": _git_sha(),
        "written_utc": f"{datetime.now(timezone.utc):%Y-%m-%d %H:%M:%S}",
        "n_vertices": mesh.n_vertices,
        "n_faces": mesh.n_faces,
        "channels": {
            name: {
                "unit": CHANNEL_UNITS.get(name, "?"),
                "min": float(np.min(arr)), "max": float(np.max(arr)),
                "mean": float(np.mean(arr)),
            } for name, arr in sorted(mesh.channels.items())
        },
    })
    if extra:
        doc.update(extra)
    path.write_text(json.dumps(doc, indent=2) + "\n", encoding="utf-8")
    return path


def export_frame(mesh, directory, stem: str = "water", *,
                 obj: bool = False, quiet: bool = False) -> dict:
    """Write ``<stem>.ply`` plus its metadata, and optionally an OBJ.

    Returns the paths written.
    """
    directory = Path(directory)
    out = {"ply": write_ply(mesh, directory / f"{stem}.ply"),
           "json": write_frame_metadata(mesh, directory / f"{stem}.json")}
    if obj:
        out["obj"] = write_obj(mesh, directory / f"{stem}.obj", quiet=quiet)
    return out


# ---------------------------------------------------------------------------
# A starting scene, for Mitsuba's Python bindings
# ---------------------------------------------------------------------------
#
# Built in three layers so none of it needs Mitsuba installed until the moment
# it is rendered:
#
#   mitsuba_scene_params   plain JSON-serialisable numbers -- camera, sun,
#                          roughness, resolution.  Computable and testable
#                          anywhere.
#   mitsuba_scene_dict     those numbers assembled into the structure
#                          `mi.load_dict` wants.  Needs Mitsuba only to build
#                          the camera transform.
#   write_mitsuba_scene    a standalone `scene.py` carrying both, so it can be
#                          imported by an existing render script or run
#                          directly.
#
# `write_mitsuba_xml` remains for the `mitsuba` command-line tool, which takes
# XML and nothing else.


def mitsuba_scene_params(water_ply, terrain_ply, *, water_mesh=None,
                         terrain_mesh=None, width: int = 1280, height: int = 720,
                         spp: int = 128, fov: float = 45.0,
                         sun_azimuth_deg: float = 135.0,
                         sun_elevation_deg: float = 35.0,
                         offshore=None) -> dict:
    """Everything the scene needs, as plain numbers.

    The camera is placed from the meshes' own bounds -- offshore, elevated,
    looking back at the waterline -- so the shoreline is framed without anyone
    guessing coordinates.  Scene units are metres and Z is up, which is why the
    camera's ``up`` is ``(0, 0, 1)`` rather than Mitsuba's usual ``(0, 1, 0)``.
    """
    ref = terrain_mesh if terrain_mesh is not None else water_mesh
    if ref is None:
        raise ValueError("pass at least one mesh so the camera can be placed")

    lo, hi = ref.bounds()
    cx, cy = 0.5 * (lo[0] + hi[0]), 0.5 * (lo[1] + hi[1])
    span = float(max(hi[0] - lo[0], hi[1] - lo[1]))

    # Stand offshore, elevated, aimed a little landward of centre so the
    # waterline stays in frame. `offshore` comes from the shore normal; the
    # default is -Y, which is the synthetic beaches' orientation and is wrong
    # for any coast that faces the other way.
    v = np.asarray(offshore if offshore is not None else (0.0, -1.0), float)
    v = v / max(float(np.hypot(*v)), 1e-9)
    target = [float(cx - 0.15 * span * v[0]), float(cy - 0.15 * span * v[1]),
              float(0.5 * (lo[2] + hi[2]))]
    origin = [float(cx + 0.55 * span * v[0]), float(cy + 0.55 * span * v[1]),
              float(hi[2] + 0.22 * span)]

    alpha = 0.1
    if water_mesh is not None and "mss" in water_mesh.channels:
        alpha = float(np.sqrt(np.mean(water_mesh.channels["mss"])))

    az, el = np.radians(sun_azimuth_deg), np.radians(sun_elevation_deg)
    sun = [float(-np.cos(az) * np.cos(el)), float(-np.sin(az) * np.cos(el)),
           float(-np.sin(el))]

    return {
        "water_ply": Path(water_ply).name,
        "terrain_ply": Path(terrain_ply).name,
        "camera": {"origin": origin, "target": target, "up": [0.0, 0.0, 1.0],
                   "fov": float(fov), "fov_axis": "x"},
        "film": {"width": int(width), "height": int(height)},
        "spp": int(spp),
        "water_alpha": alpha,
        "water_ior": 1.333,
        "terrain_reflectance": [0.52, 0.46, 0.35],
        "sky_radiance": [0.35, 0.45, 0.60],
        "offshore": [float(v[0]), float(v[1])],
        "sun": {"direction": sun, "irradiance": [4.0, 3.8, 3.4],
                "azimuth_deg": float(sun_azimuth_deg),
                "elevation_deg": float(sun_elevation_deg)},
        "max_depth": 12,
        "note": ("Placeholder BSDFs.  water_alpha is the scene mean of the "
                 "per-vertex mss channel, baked to a constant because a stock "
                 "BSDF cannot read mesh attributes; the Phase 7 plugin reads "
                 "mss per vertex instead."),
    }


def mitsuba_scene_dict(params: dict, *, base_dir=None, transform=None,
                       spp: int | None = None) -> dict:
    """Assemble ``params`` into the structure ``mi.load_dict`` accepts.

    Parameters
    ----------
    base_dir : directory the PLY filenames are relative to.  Defaults to the
        current directory, which is rarely what you want -- pass the mesh
        directory, or use the generated ``scene.py``, which resolves paths
        against its own location.
    transform : callable ``(origin, target, up) -> to_world``.  Defaults to
        ``mi.ScalarTransform4f().look_at``.

    Notes
    -----
    **Call ``mi.set_variant(...)`` before this.**  ``mi.ScalarTransform4f`` does
    not exist until a variant is selected, so building the camera transform
    fails with a confusing error if the variant is still unset.

    The ``transform`` hook exists so the dictionary's structure can be built and
    checked without Mitsuba present, which is how this function is tested in an
    environment that does not have it.
    """
    if transform is None:
        try:
            import mitsuba as mi

            def transform(o, t, u):
                return mi.ScalarTransform4f().look_at(origin=o, target=t, up=u)
        except (ImportError, AttributeError) as exc:
            raise RuntimeError(
                "mitsuba is not importable, or no variant has been selected. "
                "Call mi.set_variant(...) first, or pass transform=... to build "
                "the camera matrix yourself."
            ) from exc

    base = Path(base_dir) if base_dir is not None else Path(".")
    cam = params["camera"]

    return {
        "type": "scene",
        "integrator": {"type": "path", "max_depth": params["max_depth"]},
        "sensor": {
            "type": "perspective",
            "fov": cam["fov"],
            "fov_axis": cam["fov_axis"],
            "to_world": transform(cam["origin"], cam["target"], cam["up"]),
            "film": {
                "type": "hdrfilm",
                "width": params["film"]["width"],
                "height": params["film"]["height"],
            },
            "sampler": {
                "type": "independent",
                "sample_count": int(spp if spp is not None else params["spp"]),
            },
        },
        "sky": {"type": "constant",
                "radiance": {"type": "rgb", "value": params["sky_radiance"]}},
        "sun": {"type": "directional",
                "direction": params["sun"]["direction"],
                "irradiance": {"type": "rgb",
                               "value": params["sun"]["irradiance"]}},
        "terrain": {
            "type": "ply",
            "filename": str(base / params["terrain_ply"]),
            "bsdf": {"type": "diffuse",
                     "reflectance": {"type": "rgb",
                                     "value": params["terrain_reflectance"]}},
        },
        "water": {
            "type": "ply",
            "filename": str(base / params["water_ply"]),
            "bsdf": {"type": "roughdielectric",
                     "distribution": "beckmann",
                     "alpha": params["water_alpha"],
                     "int_ior": params["water_ior"],
                     "ext_ior": 1.0},
        },
    }


_SCENE_PY = '''"""Mitsuba scene for a pywave water + terrain pair.

Generated by `pywave.export.write_mitsuba_scene`.  Regenerate rather than edit.

UNTESTED AGAINST MITSUBA.  Mitsuba is a Phase 7 dependency and was not installed
in the environment that produced this file, so the dictionary below is written
from the documented schema and has never been loaded.  Treat it as a starting
point that will probably need a nudge.

Use it either way round:

    # as a module, from your own render script
    from scene import scene_dict
    import mitsuba as mi
    mi.set_variant("cuda_ad_rgb")
    img = mi.render(mi.load_dict(scene_dict()), spp=256)

    # or directly
    python scene.py --variant cuda_ad_rgb --spp 256 -o test.exr

The BSDFs are placeholders.  `water_alpha` is the scene mean of the per-vertex
`mss` channel, baked to a constant because a stock BSDF cannot read mesh
attributes.  The PLYs carry mss, wdir_x, wdir_y, aniso, depth, foam and wetness
per vertex, all currently unused -- consuming them is the Phase 7 plugin's job.

Before anything else, confirm Mitsuba exposes those properties at all
(cookbook 6.6):

    import mitsuba as mi
    mi.set_variant("scalar_rgb")
    print(mi.traverse(mi.load_dict({"type": "ply",
                                    "filename": "@@WATER_PLY@@"})))
"""

from __future__ import annotations

import json
from pathlib import Path

HERE = Path(__file__).resolve().parent

PARAMS = json.loads(r"""
@@PARAMS_JSON@@
""")


def scene_dict(spp=None, base_dir=None) -> dict:
    """The `mi.load_dict` structure.  Call `mi.set_variant(...)` first."""
    import mitsuba as mi

    cam = PARAMS["camera"]
    base = Path(base_dir) if base_dir is not None else HERE
    return {
        "type": "scene",
        "integrator": {"type": "path", "max_depth": PARAMS["max_depth"]},
        "sensor": {
            "type": "perspective",
            "fov": cam["fov"],
            "fov_axis": cam["fov_axis"],
            "to_world": mi.ScalarTransform4f().look_at(
                origin=cam["origin"], target=cam["target"], up=cam["up"]),
            "film": {"type": "hdrfilm",
                     "width": PARAMS["film"]["width"],
                     "height": PARAMS["film"]["height"]},
            "sampler": {"type": "independent",
                        "sample_count": int(spp or PARAMS["spp"])},
        },
        "sky": {"type": "constant",
                "radiance": {"type": "rgb", "value": PARAMS["sky_radiance"]}},
        "sun": {"type": "directional",
                "direction": PARAMS["sun"]["direction"],
                "irradiance": {"type": "rgb",
                               "value": PARAMS["sun"]["irradiance"]}},
        "terrain": {
            "type": "ply",
            "filename": str(base / PARAMS["terrain_ply"]),
            "bsdf": {"type": "diffuse",
                     "reflectance": {"type": "rgb",
                                     "value": PARAMS["terrain_reflectance"]}},
        },
        "water": {
            "type": "ply",
            "filename": str(base / PARAMS["water_ply"]),
            "bsdf": {"type": "roughdielectric",
                     "distribution": "beckmann",
                     "alpha": PARAMS["water_alpha"],
                     "int_ior": PARAMS["water_ior"],
                     "ext_ior": 1.0},
        },
    }


def render(variant: str = "cuda_ad_rgb", spp=None, out: str = "test.exr"):
    """Load and render.  Falls back to scalar_rgb if the variant is unavailable."""
    import mitsuba as mi

    try:
        mi.set_variant(variant)
    except Exception:
        print("variant %r unavailable; falling back to scalar_rgb" % variant)
        mi.set_variant("scalar_rgb")

    scene = mi.load_dict(scene_dict(spp=spp))
    image = mi.render(scene, spp=int(spp or PARAMS["spp"]))
    mi.util.write_bitmap(out, image)
    print("wrote " + out)
    return image


if __name__ == "__main__":
    import argparse

    ap = argparse.ArgumentParser(description="render the pywave test scene")
    ap.add_argument("--variant", default="cuda_ad_rgb")
    ap.add_argument("--spp", type=int, default=None)
    ap.add_argument("-o", "--out", default="test.exr")
    a = ap.parse_args()
    render(a.variant, a.spp, a.out)
'''


def write_mitsuba_scene(path, water_ply, terrain_ply, *, water_mesh=None,
                        terrain_mesh=None, params: dict | None = None,
                        **kwargs) -> Path:
    """Write a standalone ``scene.py`` plus ``scene_params.json``.

    The Python module is the primary artifact: it hands ``mi.load_dict`` a
    dictionary, which is what most Mitsuba workflows actually want, and it
    resolves the PLY paths against its own location so it works from any
    working directory.  The JSON alongside carries the same numbers for anything
    that would rather not import Python.
    """
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)

    if params is None:
        params = mitsuba_scene_params(water_ply, terrain_ply,
                                      water_mesh=water_mesh,
                                      terrain_mesh=terrain_mesh, **kwargs)

    json_path = path.with_name(path.stem + "_params.json")
    json_path.write_text(json.dumps(params, indent=2) + "\n", encoding="utf-8")

    # Simple substitution rather than %-formatting or str.format: the template
    # is Python source and contains both `%` and `{}` in its own right, so any
    # formatting mini-language would need escaping throughout and would break
    # the moment someone edited the generated code.
    body = (_SCENE_PY
            .replace("@@PARAMS_JSON@@", json.dumps(params, indent=2))
            .replace("@@WATER_PLY@@", params["water_ply"]))
    path.write_text(body, encoding="utf-8")
    return path


def write_mitsuba_xml(path, water_ply, terrain_ply, *, water_mesh=None,
                      terrain_mesh=None, params: dict | None = None,
                      **kwargs) -> Path:
    """Write an XML scene, for the ``mitsuba`` command-line renderer.

    Kept alongside the Python form because the CLI takes XML and nothing else.
    Same placeholders, same caveats.
    """
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    if params is None:
        params = mitsuba_scene_params(water_ply, terrain_ply,
                                      water_mesh=water_mesh,
                                      terrain_mesh=terrain_mesh, **kwargs)

    cam, sun = params["camera"], params["sun"]
    o, t, u = cam["origin"], cam["target"], cam["up"]
    d = sun["direction"]

    def rgb(v):
        return ", ".join(str(c) for c in v)

    # NB: `-` doubled is illegal inside an XML comment, so the note avoids it.
    xml = f"""<!--
  Starter Mitsuba 3 scene for a pywave water + terrain pair.
  UNTESTED AGAINST MITSUBA; written from the documented schema, never loaded.
  Placeholder BSDFs. alpha is the scene mean of the per-vertex mss channel,
  baked to a constant because a stock BSDF cannot read mesh attributes.
  Render:  mitsuba {path.name} -o test.exr
-->
<scene version="3.0.0">

  <integrator type="path">
    <integer name="max_depth" value="{params['max_depth']}"/>
  </integrator>

  <sensor type="perspective">
    <string name="fov_axis" value="{cam['fov_axis']}"/>
    <float name="fov" value="{cam['fov']}"/>
    <transform name="to_world">
      <lookat origin="{o[0]:.3f}, {o[1]:.3f}, {o[2]:.3f}"
              target="{t[0]:.3f}, {t[1]:.3f}, {t[2]:.3f}"
              up="{u[0]}, {u[1]}, {u[2]}"/>
    </transform>
    <film type="hdrfilm">
      <integer name="width" value="{params['film']['width']}"/>
      <integer name="height" value="{params['film']['height']}"/>
    </film>
    <sampler type="independent">
      <integer name="sample_count" value="{params['spp']}"/>
    </sampler>
  </sensor>

  <emitter type="constant">
    <rgb name="radiance" value="{rgb(params['sky_radiance'])}"/>
  </emitter>
  <emitter type="directional">
    <vector name="direction" value="{d[0]:.4f}, {d[1]:.4f}, {d[2]:.4f}"/>
    <rgb name="irradiance" value="{rgb(sun['irradiance'])}"/>
  </emitter>

  <shape type="ply" id="terrain">
    <string name="filename" value="{params['terrain_ply']}"/>
    <bsdf type="diffuse">
      <rgb name="reflectance" value="{rgb(params['terrain_reflectance'])}"/>
    </bsdf>
  </shape>

  <shape type="ply" id="water">
    <string name="filename" value="{params['water_ply']}"/>
    <bsdf type="roughdielectric">
      <string name="distribution" value="beckmann"/>
      <float name="alpha" value="{params['water_alpha']:.5f}"/>
      <float name="int_ior" value="{params['water_ior']}"/>
      <float name="ext_ior" value="1.0"/>
    </bsdf>
  </shape>

</scene>
"""
    body = xml[xml.index("<!--") + 4:xml.index("-->")]
    if "--" in body:
        raise ValueError("XML comment contains an illegal double hyphen")
    path.write_text(xml, encoding="utf-8")
    return path


# ---------------------------------------------------------------------------
# Terrain export (the Phase 4 side of the contract)
# ---------------------------------------------------------------------------


def write_terrain_export(bathy, directory) -> dict:
    """Write a :class:`~pywave.bathymetry.Bathymetry` as a Phase 4 export.

    The inverse of :meth:`~pywave.bathymetry.Bathymetry.from_export`, writing
    the six files cookbook section 4.5 specifies.  Two uses:

    * round-tripping the loader in tests without needing a real Houdini export
      to be present, which is what makes the loader testable at all on a machine
      that has not run Houdini;
    * snapshotting a synthetic basin so it can be handed to something that
      expects real terrain.

    ``shore_normal`` is written ``(2, ny, nx)``, matching this package's internal
    layout.  The section 0.4 table writes ``(ny, nx, 2)``; the loader accepts
    either, precisely because both conventions are in circulation.
    """
    directory = Path(directory)
    directory.mkdir(parents=True, exist_ok=True)
    m = bathy.meta
    ny, nx = m.shape

    np.save(directory / "terrain_z.npy",
            np.asarray(bathy.terrain_z, dtype=np.float32))
    np.save(directory / "depth.npy", np.asarray(bathy.depth, dtype=np.float32))
    np.save(directory / "sdf.npy", np.asarray(bathy.sdf, dtype=np.float32))
    np.save(directory / "shore_normal.npy",
            np.asarray(bathy.shore_normal, dtype=np.float32))

    bottom = bathy.bottom_type
    if bottom is None:
        # No sediment classification to write, so record the one distinction
        # that is actually known: wet or dry.
        bottom = (bathy.depth > 0.0).astype(np.uint8)
    np.save(directory / "bottom_type.npy", np.asarray(bottom, dtype=np.uint8))

    meta = {"x0": float(m.origin[0]), "y0": float(m.origin[1]),
            "dx": float(m.dx), "dy": float(m.dx),
            "nx": int(nx), "ny": int(ny),
            "z_w": float(m.water_level), "epsg": int(m.epsg)}
    (directory / "grid_meta.json").write_text(json.dumps(meta, indent=4) + "\n",
                                              encoding="utf-8")
    return meta
